# $env:TM_PROJECT="joijwboqwnujvyxudqez"
# $env:TM_ANONKEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvaWp3Ym9xd251anZ5eHVkcWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODc3NjM1NDQsImV4cCI6MjAwMzMzOTU0NH0.n3hiSx2r5UbRy0F0TDacrAqx1bsqVETwiJzhZNMhzM0"
$env:TM_PROJECT="https://supabase.thinkmay.net"
$env:TM_ANONKEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJyb2xlIjogImFub24iLAogICJpc3MiOiAic3VwYWJhc2UiLAogICJpYXQiOiAxNjk0MDE5NjAwLAogICJleHAiOiAxODUxODcyNDAwCn0.EpUhNso-BMFvAJLjYbomIddyFfN--u-zCf0Swj9Ac6E"